### ISSUE TITLE
Graphic Design

### ISSUE THREAD

**Issue by nunojesus** [chmjs/chameleon-sdk#14]
Hello can you give me more informations about this project? Im a graphic designer that contributes for opensource projects like yours, so if you need some help to create a logotype or other stuff just say it.

Greetings

**Comment by manico** [comment]
Hi, thank you for your interest. :)
This is a common library for our other projects. It contains components and utility functions.
We have a logotype for out main project (check it on our organisation page).

Once again, thank you. :)
