### ISSUE TITLE
Local Connector Data Source

### ISSUE THREAD

**Issue by Sneki** [chmjs/chameleon-sdk#22]
Regarding chmjs/chameleon-vuetify#50 and chmjs/chameleon-vuetify#45 list / table data source, we have an issue when local connector is selected. 
No matter which values we select inside Data Source we are always end up with all data, not just selected ones. 
The difference here is that Chameleon connector filters only data from schema.

![image](https://user-images.githubusercontent.com/6430146/44219700-0021d000-a17d-11e8-9024-38c1d7041ba5.png)

Correct me if I'm wrong but I don't see that you filter selected values inside **getSourceData** _local.js_ SDK method, or anywhere after calling this method.

**Comment by manico** [comment]
You are right. There is no filtering mock in local connector. It should me added by just using lodash filtering methods.
