### ISSUE TITLE
Complete Documentation for Implementing RESTful connector

### ISSUE THREAD

**Issue by manico** [chmjs/chameleon-sdk#26]
We need to document RESTful connector missing features in README file.

Missing features are (by priority):

- Paging (in getSourceData)
- Filtering (in getSourceData)
- Sorting (in getSourceData)
- Available methods (in getSources like `[read, write]`)

Since this should be common connector where implementation is on third-party side (as opposed to our backend connectors) this needs to be standardised so use some guidelines for filtering, paging and sorting (example: https://opensource.zalando.com/restful-api-guidelines/#introduction).

**Comment by moahmo** [comment]
Document ready for RFC is here: https://docs.google.com/document/d/1tNFxa8pJK2IVgtrw_C3w_VaXxHW5RZMZuSU5gMlIc3Q/edit#heading=h.fm69rcjtguso

Closing this issue. All comments and issues can be added to that doc.
