### ISSUE TITLE
Implement Mask in Fields

### ISSUE THREAD

**Issue by manico** [chmjs/chameleon-sdk#64]
**Is your feature request related to a problem? Please describe.**
There is no possibility to insert static text into field value. There is no way to use, for example, base url of browser window as part of the thumbnail or video stream.

**Describe the solution you'd like**
Implement `mask` as field option, same as type mapping so that we can transform field value.
Example: https://github.com/chmjs/chameleon-vuetify/issues/167

**Describe alternatives you've considered**
Implementation on widget level:
https://github.com/chmjs/chameleon-vuetify/issues/167
Bad, because it would have to be integrated to all widgets.
With data source this is implemented in one place and it is more natural.

**Additional context**
Related to data binding dialog in Builder.

**Comment by Lanchi** [comment]
`mask` property added to each schema field chmjs/chameleon-builder#341

**Comment by Lanchi** [comment]
@manico if the idea was to use mask as a simple prefix to field value when fetching data, I can proceed with the implementation.

**Comment by Lanchi** [comment]
Nvm, Ivica explained what was done on video stream 🙂

**Comment by manico** [comment]
It is not a prefix. It is a same sa ToType implementation except this will take templating function to create calculated field (mask). I can do this over the weekend.
